# Generated by Django 4.1.6 on 2023-02-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_baduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadUser',
        ),
    ]
